"""Committed basin table: regime class, attributes, and cohort membership.

Why this exists
---------------
The 2026-08-19 adversarial review found that the project's prose describes the
training population as "27 mostly-snowmelt catchments" / "snowmelt Sierra
headwaters", while the project's OWN regime rule -- `frac_snow < 0.3`, the rule
used in `make_peak_error_curve.py` -- classifies most of the configured basins
as rain-driven. There was no committed table anyone could check that against.
This script writes one.

Definitions (all taken from existing project code, not re-invented)
-------------------------------------------------------------------
regime      'rain' if frac_snow < 0.3 else 'snow'  (make_peak_error_curve.py)
train28     the 28 gauges in ca-basins-expanded.txt, i.e. the configured
            training/validation/test basin file for every flood-split run
cohort22    basins with >= 30 valid source-netCDF observation days inside the
            two flood test water years (2016-10-01..2017-09-30,
            2022-10-01..2023-09-30) -- the fixed evaluation cohort quoted with
            every median in METHODS 4.1. Determined on the lead-0 axis.
Attributes come from the Caravan attribute CSVs at
~/data/caravan-nc-extended/attributes/camels/ (`frac_snow`, `p_mean`,
`aridity_ERA5_LAND` from attributes_caravan_camels.csv; `gauge_name`, `area`,
lat/lon from attributes_other_camels.csv; mean elevation `ele_mt_sav` from
attributes_hydroatlas_camels.csv -- reported here because the manuscript claims
elevation is a static input, which the config does not include).

Usage:  source ~/opt/anaconda3/etc/profile.d/conda.sh && conda activate googlehydrology
        cd ~/Documents/Side_projects/Hydrology
        python scripts/make_basin_regime_table.py
Writes: outputs/figures/basin_regime_table.csv
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd
import xarray as xr

HYD = os.path.expanduser('~/Documents/Side_projects/Hydrology')
BASIN_LIST = f'{HYD}/central_valley_floodforecasting/ca-basins-expanded.txt'
ZARR_PATH = (f'{HYD}/runs/ca-28basin-flood-h128_1208_025528/test/'
             f'model_epoch014/test_results.zarr')
CARAVAN = os.path.expanduser('~/data/caravan-nc-extended/timeseries/netcdf/camels')
ATTR_DIR = os.path.expanduser('~/data/caravan-nc-extended/attributes/camels')
OUT = f'{HYD}/outputs/figures'

WINDOWS = [('2016-10-01', '2017-09-30'), ('2022-10-01', '2023-09-30')]
MIN_VALID_DAYS = 30
SNOW_THRESHOLD = 0.3

# Named focus basins, for readability of the committed table.
FOCUS = {
    'camels_11264500': 'Merced @ Happy Isles',
    'camels_11266500': 'Merced @ Pohono',
    'camels_11230500': 'Bear Ck',
    'camels_11237500': 'Pitman Ck',
    'camels_11381500': 'Mill Ck',
}


def main() -> None:
    basins = open(BASIN_LIST).read().split()

    car = pd.read_csv(f'{ATTR_DIR}/attributes_caravan_camels.csv').set_index('gauge_id')
    oth = pd.read_csv(f'{ATTR_DIR}/attributes_other_camels.csv').set_index('gauge_id')
    hya = pd.read_csv(f'{ATTR_DIR}/attributes_hydroatlas_camels.csv').set_index('gauge_id')

    res = xr.open_zarr(ZARR_PATH, consolidated=False).squeeze('freq')
    zarr_dates = pd.to_datetime(res['date'].values)

    rows = []
    for gid in basins:
        q = xr.open_dataset(f'{CARAVAN}/{gid}.nc')['streamflow'].to_series()
        q.index = pd.to_datetime(q.index)
        qz = q.reindex(zarr_dates)
        n_valid = int(sum(qz.loc[a:z].notna().sum() for a, z in WINDOWS))

        fs = float(car.loc[gid, 'frac_snow'])
        rows.append({
            'basin': gid,
            'gauge_name': oth.loc[gid, 'gauge_name'] if gid in oth.index else '',
            'focus_label': FOCUS.get(gid, ''),
            'frac_snow': fs,
            'regime': 'rain' if fs < SNOW_THRESHOLD else 'snow',
            'area_km2': float(oth.loc[gid, 'area']) if gid in oth.index else np.nan,
            'ele_mean_m': float(hya.loc[gid, 'ele_mt_sav']) if gid in hya.index else np.nan,
            'p_mean_mm_day': float(car.loc[gid, 'p_mean']),
            'aridity_ERA5_LAND': float(car.loc[gid, 'aridity_ERA5_LAND']),
            'gauge_lat': float(oth.loc[gid, 'gauge_lat']) if gid in oth.index else np.nan,
            'gauge_lon': float(oth.loc[gid, 'gauge_lon']) if gid in oth.index else np.nan,
            'n_valid_obs_days_flood_windows': n_valid,
            'in_train28': True,
            'in_cohort22': n_valid >= MIN_VALID_DAYS,
        })

    df = pd.DataFrame(rows).sort_values(['regime', 'frac_snow'],
                                        ascending=[True, False])

    os.makedirs(OUT, exist_ok=True)
    out_csv = f'{OUT}/basin_regime_table.csv'
    with open(out_csv, 'w') as f:
        f.write(
            f'# Basin table for the flood-split experiment, generated by '
            f'scripts/make_basin_regime_table.py.\n'
            f'# regime = rain if frac_snow < {SNOW_THRESHOLD} else snow -- the '
            f'project\'s own rule (make_peak_error_curve.py).\n'
            f'# in_train28 = member of ca-basins-expanded.txt (the configured '
            f'training/validation/test basin file).\n'
            f'# in_cohort22 = >= {MIN_VALID_DAYS} valid source-netCDF obs days '
            f'inside WY2017+WY2023; the fixed evaluation cohort.\n'
            f'# Attributes are Caravan/HydroATLAS values; ele_mean_m is reported '
            f'because it is NOT a static input in the flood config.\n'
        )
        df.to_csv(f, index=False)
    print(f'Wrote {out_csv}')

    n_rain = int((df.regime == 'rain').sum())
    n_snow = int((df.regime == 'snow').sum())
    coh = df[df.in_cohort22]
    print(f'\n28-basin training set: {n_rain} rain / {n_snow} snow')
    print(f'22-basin cohort:       {int((coh.regime == "rain").sum())} rain / '
          f'{int((coh.regime == "snow").sum())} snow  (n={len(coh)})')
    lobo = df[df.basin != 'camels_11381500']
    print(f'Mill Ck LOBO training set (27 basins): '
          f'{int((lobo.regime == "rain").sum())} rain / '
          f'{int((lobo.regime == "snow").sum())} snow')
    print(f'Mill Ck frac_snow = {float(df.loc[df.basin == "camels_11381500", "frac_snow"].iloc[0]):.3f}')

    pd.set_option('display.width', 200)
    print()
    print(df[['basin', 'gauge_name', 'frac_snow', 'regime', 'area_km2',
              'p_mean_mm_day', 'aridity_ERA5_LAND', 'in_cohort22']]
          .to_string(index=False, float_format=lambda v: f'{v:.3f}'))


if __name__ == '__main__':
    main()
